# Generated by Django 4.2.4 on 2023-08-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_accounts_register_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="register_status",
            new_name="register",
        ),
    ]
