# Generated by Django 4.2.4 on 2023-08-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_delete_purchase_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="register",
            field=models.BooleanField(
                default=False, unique=True, verbose_name="간편 결제 등록 여부"
            ),
        ),
    ]
