# Generated by Django 4.2.4 on 2023-08-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_fix_user_posts_register_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="register",
            field=models.BooleanField(default=False, verbose_name="간편 결제 등록 여부"),
        ),
    ]
