# Generated by Django 4.2.4 on 2023-08-07 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post-image', verbose_name='제품 이미지')),
                ('name', models.CharField(max_length=128, verbose_name='제품 이름')),
                ('price', models.IntegerField(default=0, verbose_name='제품 가격')),
                ('category', models.CharField(choices=[('cate1', '패션의류/잡화'), ('cate2', '뷰티'), ('cate3', '식품'), ('cate4', '생필품'), ('cate5', '홈데코'), ('cate6', '건강')], default='cate1', max_length=20, verbose_name='카테고리명')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=16, verbose_name='카드 번호')),
                ('cvc', models.CharField(max_length=3, verbose_name='카드 cvc')),
                ('validDate', models.DateField(auto_now_add=True, verbose_name='유효기간')),
                ('pw', models.CharField(max_length=4, verbose_name='카드 비밀번호')),
                ('balance', models.IntegerField(default=500000, verbose_name='카드 잔액')),
                ('register', models.BooleanField(default=False, verbose_name='간편 결제 등록 여부')),
            ],
            options={
                'unique_together': {('num',)},
            },
        ),
    ]
