# Generated by Django 4.2.4 on 2023-08-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(choices=[('type1', '일반결제'), ('type2', '간편결제')], default='type1', max_length=20, verbose_name='결제 방식'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total',
            field=models.IntegerField(default=0, verbose_name='총 가격'),
        ),
    ]
