# Generated by Django 4.2.4 on 2023-08-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_addTotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.CharField(default='clo1', max_length=10, unique=True, verbose_name='커스텀 ID'),
        ),
    ]
