# Generated by Django 4.2.4 on 2023-08-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_addProductId'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.CharField(max_length=10, verbose_name='커스텀 ID'),
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('product_id',)},
        ),
    ]
