# Generated by Django 4.2.4 on 2023-08-10 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_card_unique_together_card_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='커스텀 ID'),
        ),
    ]
