# Generated by Django 4.2.4 on 2023-08-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_addPrimaryKey'),
    ]
