# Generated by Django 4.2.4 on 2023-08-10 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_limitCount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post-image', verbose_name='구매 제품 이미지')),
                ('name', models.CharField(max_length=128, verbose_name='구매 제품 이름')),
                ('price', models.IntegerField(default=0, verbose_name='구매 제품 가격')),
                ('category', models.CharField(choices=[('cate1', '패션의류/잡화'), ('cate2', '뷰티'), ('cate3', '식품'), ('cate4', '생필품'), ('cate5', '홈데코'), ('cate6', '건강')], default='cate1', max_length=20, verbose_name='카테고리명')),
                ('count', models.IntegerField(default=1, verbose_name='구매 제품 개수')),
                ('total', models.IntegerField(default=0, verbose_name='총 가격')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='구매 날짜와 시각')),
                ('purchase_type', models.CharField(choices=[('type1', '일반결제'), ('type2', '간편결제')], default='type1', max_length=20, verbose_name='결제 방식')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.products')),
            ],
        ),
    ]
