# Generated by Django 4.2.4 on 2023-08-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_updateProductFK'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='register',
        ),
        migrations.AddField(
            model_name='purchase',
            name='register',
            field=models.BooleanField(default=False, verbose_name='간편 결제 등록 여부'),
        ),
    ]
