# Generated by Django 4.2.4 on 2023-08-12 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_purchase_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="validDate",
            field=models.DateField(
                default=datetime.datetime(2024, 8, 1, 0, 0), verbose_name="유효기간"
            ),
        ),
    ]
