# Generated by Django 4.2.4 on 2023-08-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_fix_validDate_column"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="register",
        ),
    ]
