# Generated by Django 4.2.4 on 2023-08-17 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0014_delete_purchase_register"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="register",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="register_purchases",
                to=settings.AUTH_USER_MODEL,
                to_field="register",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_purchases",
                to="posts.products",
            ),
        ),
    ]
