# Generated by Django 4.2.4 on 2023-08-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0016_add_purchase_register_Boolean"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="register",
        ),
    ]
